name: sync-fork

on:
  schedule:
    - cron: "0 5,17 * * *" # 每日5点和17点执行
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "sync_fork.yaml"  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION_FILE: ${{ github.workspace }}/sodium_version
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'Rzdpai/sodium-fabric-fix-holy'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'dev'

      - name: Configure Git user
        run: |
          git config user.email "3420176748@qq.com"
          git config user.name "RzdPai"

      - name: Fetch latest changes from the source repository
        run: |
          git fetch https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/CaffeineMC/sodium-fabric.git dev
          git merge FETCH_HEAD --allow-unrelated-histories

      - name: Push changes to the target repository
        run: |
          git push origin dev

      - name: Run workflow release
        if: success() || failure()
        run: |
          gh workflow run release.yaml -R Rzdpai/sodium-fabric-fix-holy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}